steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - deploy
      - releases
      - create
      - error-app-release-${BUILD_ID}
      - --delivery-pipeline=error-app-pipeline
      - --region=us-central1
      - --images=IMAGE=${_IMAGE}
      - --skaffold-file=skaffold.yaml
      - --source=.
substitutions:
  _IMAGE: gcr.io/YOUR_PROJECT_ID/error/error:${SHORT_SHA}
images:
  - gcr.io/YOUR_PROJECT_ID/error/error:${SHORT_SHA}
