steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - deploy
      - releases
      - create
      - error-app-release-${BUILD_ID}
      - --delivery-pipeline=error-pipeline
      - --region=asia-southeast1
      - --images=image=${_IMAGE}
      - --skaffold-file=skaffold.yaml
      - --source=.
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/mlfsi-jupiter-apollo/error/error:${SHORT_SHA}

images:
  - asia-southeast1-docker.pkg.dev/mlfsi-jupiter-apollo/error/error:${SHORT_SHA}
