apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preprod
  annotations:
    deploy.cloud.google.com/target-project: mlfsi-altair-phoenix
  labels:
    environment: preprod
spec:
  run:
    location: asia-southeast1
  render:
    renderEngine: CLOUD_DEPLOY
