apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
  annotations:
    deploy.cloud.google.com/target-project: mlfsi-astrid-taurus
  labels:
    environment: production
spec:
  run:
    location: asia-southeast1
  render:
    renderEngine: CLOUD_DEPLOY
