apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  labels:
    environment: dev
description: running in jupiter-apollo project
run:
  location: asia-southeast1
  serviceAccount: id-29080125-clouddeploy-sa@mlfsi-jupiter-apollo.iam.gserviceaccount.com
