apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
  labels:
    environment: qa
description: running in altair-phoenix project
run:
  location: asia-southeast1
  serviceAccount: cloud-deploy-sa@mlfsi-polaris-celestino.iam.gserviceaccount.com
