apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  labels:
    environment: prod
description: running in astrid-taurus project
run:
  location: asia-southeast1
  serviceAccount: cloud-deploy-sa@mlfsi-polaris-celestino.iam.gserviceaccount.com
