apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
  labels:
    environment: qa
description: QA environment running in Celestino project
run:
  location: projects/mlfsi-jupiter-celestino/locations/asia-southeast1
